### ISSUE TITLE
no longer works with RA 0.7

### ISSUE THREAD

**Issue by fmh** [rs-pro/rails_admin_state#9]
undefined method `state_path' for #RailsAdmin::Config::Fields::Types::State:0x007fdb9f964498
![capture d ecran 2015-09-20 a 16 14 09](https://cloud.githubusercontent.com/assets/56861/9981095/b05a4994-5fb2-11e5-85ad-8f20b9267e19.png)

**Comment by glebtv** [comment]
works fine, see readme https://github.com/rs-pro/rails_admin_state#usage
